### ISSUE TITLE
Info on mining SBC wrong

### ISSUE THREAD

**Issue by shohamessi** [turtlecoin/turtlecoin-wiki#113]
--algo= doesn’t seem to be working, but -a does. Also you should change url and username and password to -o, -u and -p respectively.

**Comment by Sajo811** [comment]
Fixed in #114, thanks! :D

**Comment by shohamessi** [comment]
It’s still wrong. There’s no =, only spaces. 

e.g.  -a cryptonight-lite -u TRTLxxxxx

**Comment by ZedPea** [comment]
MOMMMMM

**Comment by Sajo811** [comment]
Fixed in #115?

**Comment by ZedPea** [comment]
--variant=1 ?

**Comment by shohamessi** [comment]
Yea that works.

**Comment by ZedPea** [comment]
Good stuff

**Comment by shohamessi** [comment]
Yep perfect!
